name: Run Cypress Tests Inside Docker

on:
  push:
    branches:
      - default
  pull_request:
    branches:
      - default
  schedule:
    - cron: '*/5 * * * *' # Запуск кожні 5 хвилин

jobs:
  cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results
